import type { Config, Context } from '@netlify/functions'
import { db } from '../../db/index.js'
import { users, students, attendance, alerts, pendingVerifications } from '../../db/schema.js'
import { and, desc, eq, gte, ilike, lte, or, sql } from 'drizzle-orm'
import bcrypt from 'bcryptjs'
import { SignJWT, jwtVerify } from 'jose'
import * as XLSX from 'xlsx'

const json = (data: unknown, status = 200) => Response.json(data, { status })
const fail = (message: string, status = 400, code = 'REQUEST_FAILED') => json({ success: false, message, code }, status)
const env = (key: string, fallback = '') => Netlify.env.get(key) || fallback
const secret = () => new TextEncoder().encode(env('JWT_SECRET', 'local-development-secret-change-me'))
const refreshSecret = () => new TextEncoder().encode(env('JWT_REFRESH_SECRET', 'local-refresh-secret-change-me'))
const token = (u: typeof users.$inferSelect, refresh = false) => new SignJWT({ sub: u.id, role: u.role, username: u.username, type: refresh ? 'refresh' : 'access' }).setProtectedHeader({ alg: 'HS256' }).setIssuedAt().setExpirationTime(refresh ? '30d' : '7d').sign(refresh ? refreshSecret() : secret())
async function current(req: Request) { const raw = req.headers.get('authorization')?.replace('Bearer ', ''); if (!raw) return null; try { const { payload } = await jwtVerify(raw, secret()); return payload } catch { return null } }
async function requireUser(req: Request) { const auth = await current(req); if (!auth?.sub) throw new Response(JSON.stringify({ success: false, message: 'Authentication required', code: 'UNAUTHORIZED' }), { status: 401, headers: { 'content-type': 'application/json' } }); return auth }
const today = () => new Date().toISOString().slice(0, 10)
const sessions = () => env('CLASS_SESSIONS', '09:00-10:00,10:00-11:00,14:00-15:00,15:00-16:00').split(',')
function activeSession(now = new Date()) { const hm = now.toISOString().slice(11, 16); const value = sessions().find((s) => { const [a, b] = s.split('-'); return hm >= a && hm <= b }); return value || null }
function distance(a: number, b: number, c: number, d: number) { const r = 6371e3, p1 = a * Math.PI / 180, p2 = c * Math.PI / 180, dp = (c-a)*Math.PI/180, dl=(d-b)*Math.PI/180; const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)) }
async function addAlert(type: string, severity: string, message: string, context: Context, studentId?: string) { await db.insert(alerts).values({ type, severity, message, ipAddress: context.ip, studentId, userAgent: '' }) }
async function updateStats(studentId:string){const rows=await db.select({status:attendance.status,count:sql<number>`count(*)::int`}).from(attendance).where(eq(attendance.studentId,studentId)).groupBy(attendance.status);const stats:any={total:0,present:0,late:0,absent:0,partial:0,percentage:0};for(const r of rows){stats[r.status]=r.count;stats.total+=r.count}stats.percentage=stats.total?Math.round(((stats.present+stats.late*.8+stats.partial*.5)/stats.total)*100):0;await db.update(students).set({attendanceStats:stats,updatedAt:new Date()}).where(eq(students.id,studentId))}
async function recognize(image: Blob) { const form = new FormData(); form.append('image', image, 'capture.jpg'); const response = await fetch(`${env('FLASK_URL', 'http://localhost:5001')}/recognize`, { method: 'POST', body: form }); if (!response.ok) throw new Error('AI service unavailable'); return response.json() as Promise<any> }
async function security(req: Request, context: Context, form: FormData) {
  const lat = Number(form.get('latitude')), lng = Number(form.get('longitude')); const clat = Number(env('COLLEGE_LAT')), clng = Number(env('COLLEGE_LNG'));
  if (clat && clng && (!lat || !lng || distance(lat,lng,clat,clng) > Number(env('GEOFENCE_RADIUS_METERS','200')))) { await addAlert('geofence_violation','high','Attendance attempt outside campus',context); throw fail('Outside campus geofence',403,'GEOFENCE_VIOLATION') }
  const allowed = env('ALLOWED_WIFI_IPS').split(',').map(v=>v.trim()).filter(Boolean); if (allowed.length && !allowed.some(v=>context.ip.startsWith(v.replace(/\/\d+$/,'')))) { await addAlert('network_violation','high','Attendance attempt outside college network',context); throw fail('Connect to college WiFi',403,'NETWORK_VIOLATION') }
  const session = activeSession(); if (!session && env('ENFORCE_CLASS_SESSIONS','true') !== 'false') throw fail('Outside class hours',403,'NO_ACTIVE_SESSION'); return session || 'Open session'
}

export default async (req: Request, context: Context) => {
 try {
  const url = new URL(req.url), path = url.pathname.replace(/^\/api\/?/, ''), method = req.method
  if (path === 'health') return json({ status: 'ok', service: 'AttendAI API', timestamp: new Date().toISOString() })
  if (path === 'auth/login' && method === 'POST') {
    const body = await req.json() as any; let [u] = await db.select().from(users).where(or(eq(users.username, body.username || ''), eq(users.email, body.username || ''))).limit(1)
    if (!u && body.username === 'admin' && env('ALLOW_DEFAULT_ADMIN','true') === 'true') { [u] = await db.insert(users).values({ username:'admin',email:env('ADMIN_EMAIL','admin@attendai.local'),password:await bcrypt.hash(env('DEFAULT_ADMIN_PASSWORD','Admin@123'),12),role:'admin' }).returning() }
    if (!u || !u.isActive) return fail('Invalid credentials',401,'INVALID_CREDENTIALS'); if (u.lockUntil && u.lockUntil > new Date()) return fail('Account temporarily locked',423,'ACCOUNT_LOCKED')
    if (!await bcrypt.compare(body.password || '',u.password)) { const n=u.failedLoginAttempts+1; await db.update(users).set({ failedLoginAttempts:n,lockUntil:n>=5?new Date(Date.now()+15*60e3):null }).where(eq(users.id,u.id)); return fail('Invalid credentials',401,'INVALID_CREDENTIALS') }
    const accessToken=await token(u), refreshToken=await token(u,true); await db.update(users).set({failedLoginAttempts:0,lockUntil:null,refreshToken:await bcrypt.hash(refreshToken,8),lastLogin:new Date()}).where(eq(users.id,u.id)); return json({success:true,accessToken,refreshToken,user:{id:u.id,username:u.username,email:u.email,role:u.role}})
  }
  if (path === 'auth/refresh' && method === 'POST') { const { refreshToken }=await req.json() as any; try { const {payload}=await jwtVerify(refreshToken,refreshSecret()); const [u]=await db.select().from(users).where(eq(users.id,String(payload.sub))).limit(1); if(!u?.refreshToken || !await bcrypt.compare(refreshToken,u.refreshToken)) return fail('Invalid refresh token',401); const accessToken=await token(u), next=await token(u,true); await db.update(users).set({refreshToken:await bcrypt.hash(next,8)}).where(eq(users.id,u.id)); return json({success:true,accessToken,refreshToken:next}) } catch{return fail('Invalid refresh token',401)} }
  if (path === 'session/status') return json({success:true,isSessionActive:!!activeSession(),currentSession:activeSession(),serverTime:new Date().toISOString()})
  if ((path === 'attendance/mark' || path === 'attendance/exit') && method === 'POST') { const form=await req.formData(), session=await security(req,context,form), image=form.get('image'); if(!(image instanceof Blob)) return fail('Camera image required',422); let ai:any; try{ai=await recognize(image)}catch{ return fail('AI service unavailable',503,'AI_UNAVAILABLE') } if(!ai.livenessDetected){await addAlert('liveness_failure','high',ai.reason||'Liveness check failed',context);return fail(ai.reason||'Liveness check failed',422,'LIVENESS_FAILED')} if(!ai.recognized||!ai.studentId){await addAlert('unknown_face','medium','Unknown face detected',context);return fail('Face not recognized',404,'UNKNOWN_FACE')}
    const [student]=await db.select().from(students).where(and(eq(students.id,ai.studentId),eq(students.isActive,true))).limit(1); if(!student)return fail('Student is inactive or missing',404); const [record]=await db.select().from(attendance).where(and(eq(attendance.studentId,student.id),eq(attendance.attendanceDate,today()),eq(attendance.session,session))).limit(1)
    if(path.endsWith('exit')) { if(!record)return fail('No active check-in found',409); if(record.exitTime)return fail('Already checked out',409); const exitTime=new Date(), duration=Math.round((exitTime.getTime()-record.entryTime.getTime())/60000); const [updated]=await db.update(attendance).set({exitTime,duration,status:duration<30?'partial':record.status,updatedAt:new Date()}).where(eq(attendance.id,record.id)).returning(); await updateStats(student.id); return json({success:true,message:'Check-out recorded',student,attendance:updated,confidence:ai.confidence}) }
    if(record)return fail('Already marked for this session',409,'DUPLICATE_ATTENDANCE'); const [start]=session.split('-'),[sh,sm]=start.split(':').map(Number), startTime=new Date();startTime.setUTCHours(sh,sm,0,0);const status=(Date.now()-startTime.getTime())/60000>Number(env('LATE_THRESHOLD_MINUTES','10'))?'late':'present'; const [created]=await db.insert(attendance).values({studentId:student.id,attendanceDate:today(),entryTime:new Date(),session,status,verified:true,verificationStatus:'initial_passed',verificationConfidence:ai.confidence,location:{latitude:Number(form.get('latitude')),longitude:Number(form.get('longitude'))},ipAddress:context.ip,userAgent:req.headers.get('user-agent')||'',method:'face'}).returning(); await updateStats(student.id); return json({success:true,message:'Attendance marked',student,attendance:created,confidence:ai.confidence},201)
  }
  const auth=await requireUser(req)
  if(path==='session/live-feed'){const rows=await db.select({student:students,status:attendance.status,entryTime:attendance.entryTime}).from(attendance).innerJoin(students,eq(attendance.studentId,students.id)).where(eq(attendance.attendanceDate,today())).orderBy(desc(attendance.entryTime)).limit(20);const pending=await db.select().from(pendingVerifications).where(eq(pendingVerifications.status,'pending'));const encoder=new TextEncoder(),payload=JSON.stringify({presentToday:rows.length,events:rows,pendingVerifications:pending});return new Response(new ReadableStream({start(controller){controller.enqueue(encoder.encode(`event: snapshot\ndata: ${payload}\n\n`));controller.close()}}),{headers:{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'}})}
  if(path==='session/verify-random'&&method==='POST'){const form=await req.formData(),image=form.get('image'),verificationId=String(form.get('verificationId')||'');if(!(image instanceof Blob))return fail('Camera image required',422);const [pending]=await db.select().from(pendingVerifications).where(and(eq(pendingVerifications.id,verificationId),eq(pendingVerifications.status,'pending'))).limit(1);if(!pending)return fail('Verification request expired',404);const ai=await recognize(image);const passed=ai.recognized&&ai.livenessDetected&&ai.studentId===pending.studentId;await db.update(pendingVerifications).set({status:passed?'passed':'failed'}).where(eq(pendingVerifications.id,pending.id));await db.update(attendance).set({verified:passed,verificationStatus:passed?'passed':'failed',status:passed?sql`${attendance.status}`:'partial',verificationConfidence:ai.confidence,updatedAt:new Date()}).where(eq(attendance.id,pending.attendanceId));if(!passed){await addAlert('random_verify_fail','high','Random verification failed — attendance marked partial',context,pending.studentId);return fail('Verification failed — attendance marked as partial',422)}return json({success:true,message:'Verification passed'})}
  if(path==='auth/me') { const [u]=await db.select({id:users.id,username:users.username,email:users.email,role:users.role}).from(users).where(eq(users.id,String(auth.sub))); return json({success:true,user:u}) }
  if(path==='auth/logout'&&method==='POST'){await db.update(users).set({refreshToken:null}).where(eq(users.id,String(auth.sub)));return json({success:true})}
  if(path==='auth/register'&&method==='POST'){if(auth.role!=='admin')return fail('Admin access required',403);const b=await req.json() as any;const [u]=await db.insert(users).values({username:b.username,email:b.email,password:await bcrypt.hash(b.password,12),role:b.role||'teacher'}).returning({id:users.id,username:users.username,email:users.email,role:users.role});return json({success:true,user:u},201)}
  if(path==='students'&&method==='GET'){const q=url.searchParams.get('search');const where=q?or(ilike(students.name,`%${q}%`),ilike(students.rollNumber,`%${q}%`)):undefined;const data=await db.select().from(students).where(where).orderBy(desc(students.createdAt));return json({success:true,students:data,total:data.length})}
  if(path==='students'&&method==='POST'){const b=await req.json() as any;const [s]=await db.insert(students).values({...b,semester:Number(b.semester),registeredBy:String(auth.sub)}).returning();return json({success:true,student:s},201)}
  const studentMatch=path.match(/^students\/([^/]+)$/); if(studentMatch&&method==='PUT'){const b=await req.json() as any;const [s]=await db.update(students).set({...b,semester:Number(b.semester),updatedAt:new Date()}).where(eq(students.id,studentMatch[1])).returning();return json({success:true,student:s})} if(studentMatch&&method==='DELETE'){await db.update(students).set({isActive:false,updatedAt:new Date()}).where(eq(students.id,studentMatch[1]));return json({success:true,message:'Student deactivated'})}
  const historyMatch=path.match(/^students\/([^/]+)\/attendance$/);if(historyMatch&&method==='GET'){const rows=await db.select().from(attendance).where(eq(attendance.studentId,historyMatch[1])).orderBy(desc(attendance.entryTime));return json({success:true,records:rows,total:rows.length})}
  const faceMatch=path.match(/^students\/([^/]+)\/register-face$/); if(faceMatch&&method==='POST'){const f=await req.formData(), images=f.getAll('images');if(images.length<5||images.length>10)return fail('Capture between 5 and 10 images',422);const outbound=new FormData();images.forEach((i,n)=>outbound.append('images',i as Blob,`capture-${n}.jpg`));outbound.append('studentId',faceMatch[1]);const response=await fetch(`${env('FLASK_URL','http://localhost:5001')}/train`,{method:'POST',body:outbound});const result:any=await response.json();if(!response.ok||!result.success)return fail(result.message||'Face training failed',422);await db.update(students).set({isFaceRegistered:true,faceEncodingRef:result.encodingRef,updatedAt:new Date()}).where(eq(students.id,faceMatch[1]));return json({success:true,...result})}
  if(path==='attendance'&&method==='GET'||path==='attendance/today'){const rows=await db.select({id:attendance.id,date:attendance.attendanceDate,entryTime:attendance.entryTime,exitTime:attendance.exitTime,duration:attendance.duration,session:attendance.session,status:attendance.status,verified:attendance.verified,method:attendance.method,student:students}).from(attendance).innerJoin(students,eq(attendance.studentId,students.id)).where(path.endsWith('today')?eq(attendance.attendanceDate,today()):undefined).orderBy(desc(attendance.entryTime));return json({success:true,records:rows,total:rows.length})}
  if(path==='attendance/manual'&&method==='POST'){const b=await req.json() as any;const [a]=await db.insert(attendance).values({studentId:b.studentId,attendanceDate:b.date||today(),entryTime:new Date(),session:b.session||'Manual',status:b.status||'present',verified:true,verificationStatus:'manual',method:'manual'}).returning();return json({success:true,attendance:a},201)}
  if(path==='attendance/alerts'&&method==='GET'){const rows=await db.select().from(alerts).orderBy(desc(alerts.createdAt));return json({success:true,alerts:rows})} const resolve=path.match(/^attendance\/alerts\/([^/]+)\/resolve$/);if(resolve&&method==='PATCH'){const [a]=await db.update(alerts).set({isResolved:true,resolvedBy:String(auth.sub),resolvedAt:new Date()}).where(eq(alerts.id,resolve[1])).returning();return json({success:true,alert:a})}
  if(path==='dashboard/summary'){const [s]=await db.select({total:sql<number>`count(*)::int`,active:sql<number>`count(*) filter(where ${students.isActive})::int`,registered:sql<number>`count(*) filter(where ${students.isFaceRegistered})::int`}).from(students);const [p]=await db.select({present:sql<number>`count(*)::int`}).from(attendance).where(eq(attendance.attendanceDate,today()));const [a]=await db.select({count:sql<number>`count(*)::int`}).from(alerts).where(eq(alerts.isResolved,false));return json({success:true,totalStudents:s.total,activeStudents:s.active,faceRegistered:s.registered,pendingRegistration:s.total-s.registered,todayPresent:p.present,todayAbsent:Math.max(0,s.active-p.present),attendanceRate:s.active?Math.round(p.present/s.active*100):0,unresolvedAlerts:a.count})}
  if(path==='dashboard/recent-activity'){const rows=await db.select({student:students,status:attendance.status,entryTime:attendance.entryTime}).from(attendance).innerJoin(students,eq(attendance.studentId,students.id)).orderBy(desc(attendance.entryTime)).limit(8);return json({success:true,activity:rows})}
  if(path==='dashboard/attendance-trend'){const rows=await db.select({date:attendance.attendanceDate,count:sql<number>`count(*)::int`}).from(attendance).where(gte(attendance.attendanceDate,new Date(Date.now()-30*864e5).toISOString().slice(0,10))).groupBy(attendance.attendanceDate).orderBy(attendance.attendanceDate);return json({success:true,trend:rows})}
  if(path==='dashboard/department-stats'){const rows=await db.select({department:students.department,count:sql<number>`count(${attendance.id})::int`}).from(students).leftJoin(attendance,eq(attendance.studentId,students.id)).groupBy(students.department);return json({success:true,departments:rows})}
  if(path==='dashboard/low-attendance'){const rows=await db.select().from(students).where(sql`(${students.attendanceStats}->>'percentage')::numeric < 75`).limit(10);return json({success:true,students:rows})}
  if(path==='export/attendance'){const rows=await db.select({student:students.name,rollNumber:students.rollNumber,department:students.department,date:attendance.attendanceDate,entry:attendance.entryTime,exit:attendance.exitTime,duration:attendance.duration,session:attendance.session,status:attendance.status,verified:attendance.verified,method:attendance.method}).from(attendance).innerJoin(students,eq(attendance.studentId,students.id));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Attendance');const csv=url.searchParams.get('format')==='csv';const data=XLSX.write(wb,{type:'buffer',bookType:csv?'csv':'xlsx'});return new Response(data,{headers:{'content-type':csv?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','content-disposition':`attachment; filename=attendance.${csv?'csv':'xlsx'}`}})}
  const reportMatch=path.match(/^export\/student-report\/([^/]+)$/);if(reportMatch){const [student]=await db.select().from(students).where(eq(students.id,reportMatch[1]));const rows=await db.select().from(attendance).where(eq(attendance.studentId,reportMatch[1])).orderBy(desc(attendance.entryTime));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{student:student?.name,rollNumber:student?.rollNumber,...(student?.attendanceStats as object)}]),'Summary');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'History');return new Response(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),{headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','content-disposition':`attachment; filename=student-report.xlsx`}})}
  return fail('Route not found',404,'NOT_FOUND')
 } catch(error:any) { if(error instanceof Response)return error; console.error(error); return fail(error?.message==='Failed query'?'Database operation failed':error?.message||'Internal server error',500,'SERVER_ERROR') }
}
export const config: Config={path:'/api/*'}
